name: lint-and-test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: "Lint and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47.2

      - name: test
        run: go test -v ./...
